apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: full-woodpecker-python
  janus-idp.io/tekton: full-woodpecker-python
  backstage.io/kubernetes-id: full-woodpecker-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: full-woodpecker-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
