apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: full-woodpecker-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: full-woodpecker-python 
  name: full-woodpecker-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: full-woodpecker-python 
